version: '3.7'

services:
  client:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3000:3001
    environment:
      - NODE_ENV=development
      - REACT_APP_SERVICE_URL=http://localhost
      - CHOKIDAR_USEPOLLING=true
